spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe     #Oracle XE 접속 
    username: scott                              #DB 사용자명
    password: tiger                              #DB 비밀번호
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:                                   
      maximum-pool-size: 10                 
      minimum-idle: 5                          
      idle-timeout: 30000                    
      connection-timeout: 30000                
      pool-name: HikariPool                  

  jpa:
    hibernate:
      ddl-auto: create-drop                            #테스트: create-drop, 운영: update, validate 권장             
    show-sql: true                           
    properties:
      hibernate:
        format_sql: true                     
        dialect: org.hibernate.dialect.OracleDialect   