spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe         # Oracle XE 접속 URL
    username: scott                                  # DB 사용자명
    password: tiger                                  # DB 비밀번호
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:                                   
      maximum-pool-size: 10                 
      minimum-idle: 5                          
      idle-timeout: 30000                    
      connection-timeout: 30000                
      pool-name: HikariPool                  

  jpa:
    hibernate:
      ddl-auto: create-drop        # 테스트 : create-drop , 운영 : update , validate권장               
    show-sql: true                           
    properties:
      hibernate:
        format_sql: true                     
        dialect: org.hibernate.dialect.OracleDialect  

  servlet:
    multipart:            # 파일 업로드 설정
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB      

 

# Mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.thejoa703.domain

file:                    #파일 업로드 디렉토리 설정
  upload-dir: uploads

#server:         서버 포트 설정        
#  port: 8484

